version: '3'

services:
  database:
    image: bitnami/postgresql
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gym-db